name: Unit Test Compile and Upload to Repository

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
                 persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
                 fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - name: Build unit.c
        run: gcc -o unitTest unitTest.c

      - name: Commit changes
        run: |
          git config user.name mregungor
          git config user.email emre.gungor@ksbu.edu.tr
          git add .
          git commit -m "generated"
          git push 
