name: Unit Test Compilation-Artifact

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Klonlama
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential

    - name: Unit Test Compile
      run: |
        gcc -o unitTest unitTest.c

    - name: Sonucu yükle
      uses: actions/upload-artifact@v2
      with:
        name: test-sonucu
        path: not.txt
